apiVersion: v1
kind: Service
metadata:
  name: graphite
spec:
  selector:
    app: graphite
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
    - name: statsd
      port: 8125
      targetPort: 8125
      protocol: UDP
  type: NodePort
