apiVersion: v1
kind: Service
metadata:
  name: graphite
spec:
  selector:
    app: graphite
  ports:
    - name: graphite
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: statsd
spec:
  selector:
    app: graphite
  ports:
    - name: statsd
      port: 8125
      targetPort: 8125
      protocol: UDP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite
spec:
  selector:
    matchLabels:
      app: graphite
  replicas: 1
  template:
    metadata:
      labels:
        app: graphite
    spec:
      containers:
      - name: graphite
        image: graphiteapp/graphite-statsd
        ports:
        - containerPort: 80
        - containerPort: 2003
        - containerPort: 8125
