apiVersion: v1
kind: Service
metadata:
  name: scylla
spec:
  selector:
    app: scylla
  ports:
  - port: 9044
    targetPort: 9042
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylla
spec:
  serviceName: scylla
  selector:
    matchLabels:
      app: scylla
  replicas: 1
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
      - name: scylla
        image: scylladb/scylla:2.1.0
        args:
        - "--broadcast-rpc-address"
        - "localhost:9044"
        - "--memory"
        - "1G"
        - "--overprovisioned"
        - "1"
        ports:
        - containerPort: 7000
        - containerPort: 7001
        - containerPort: 9042
        - containerPort: 9160
        - containerPort: 10000
        volumeMounts:
        - name: scylladb
          mountPath: /var/lib/scylla
  volumeClaimTemplates:
    - metadata:
        name: scylladb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
