apiVersion: v1
kind: Service
metadata:
  name: scylla
spec:
  selector:
    app: scylla
  ports:
  - port: 9042
    targetPort: 9042
    protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
spec:
  selector:
    matchLabels:
      app: scylla
  replicas: 1
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
      - name: scylla
        image: scylladb/scylla:2.0.2
        args: ["--broadcast-rpc-address", "localhost:9042"]
        ports:
        - containerPort: 9042
